### ISSUE TITLE
[Crash] [1.12.2] DynamicSurroundingsHUDs Crash with Serene Seasons 1.2.17

### ISSUE THREAD

**Issue by CactusDuud** [OreCruncher/DynamicSurroundingsHuds#8]
[Pastebin](https://pastebin.com/xBzCDUb9)

I think Serene Seasons changed some of their internals.

**Comment by DemonfangArun** [comment]
https://paste.dimdev.org/aduyeyodeb.mccrash

Just chiming in that I ran into this too. It appears serene seasons has acknowledged it exists because there's a warning on x.17 about it.

**Comment by OreCruncher** [comment]
FYI - Not getting this with 1.12.18
